language: nix
nix: 2.3.7
sudo: false
env:
  global:
  - CACHIX_CACHE=shmish111
  - secure: ho70wVCO9GZ24mxaqF2WdR5SBwYm9OLR5ljoicn5J4sv6zhC8h/A1YLSJ4FmhZ1fEF8VnAasBCR2R/dO7+fHsYyc785qHnAUBcsuEPPmKyO+N7VWFfzbJjG0BqsOV+2G/TTVrsfoNmYSu7Aes/pt8CoTTvhvdJLRKibak5ZcVmu5UgKOn/H7jY34skvhFU4pWRMjeTpf+Oadicj+YdGJCfr6T15ZvKlRMiIPyhtd6uoHt8YGI2wr9uaDlqoTV/4Vess1e97AIMsc/tP/qvBXs6wTp9pyCmk5ylP/BbvPx9jgrJsnT92BFQ137qNsnFHOX2jpkRIojRc0hmQd/g5N7pf2ViGXZouQBu+cSqQOFQOmwDcv3JuaD45kQ10JEWt7Kod4R8NkSHPAx7F9wNm556KMxLJmIpj2LyTKSoRDiyz7CWDCxriJNWfYD9xPJwYOso6sD//PYW2HQ1h6SGYEnz8QCdmk5U89HkeKbEs98lHTvaf9sl13tVuZg9HWbk0JRF3v+r8mlT0vfFxqdCEOdn+Rpd/gGp8IXQB7fYB+q3ANu3BvzK+TsTbAljEcEVs2fdJ9usJm6edcJ8MQDMapD5tvWjTduGUzkVUtOn9DChat89q7Nj2qld81i8/eIdBiv86FtSeJWdMq0moEMquSNUtdSslZ87SoqpelpT/iKdE=
install:
- echo "trusted-users = $USER" | sudo tee -a /etc/nix/nix.conf
- sudo systemctl restart nix-daemon
- nix-env -iA nixpkgs.cachix
- cachix use $CACHIX_CACHE
- nix path-info --all > /tmp/store-path-pre-build
script:
- nix-build
- nix-shell --run "echo nix-shell successfully entered"
after_success:
- comm -13 <(sort /tmp/store-path-pre-build | grep -v '\.drv$') <(nix path-info --all
  | grep -v '\.drv$' | sort) | cachix push $CACHIX_CACHE
